language: php

branches:
  only:
    - master
    - dev

# list any PHP version you want to test against
php:
  - '7.0'
  - '7.1'

before_script:
  - composer self-update

install:
  - composer global require "squizlabs/php_codesniffer $PHPCS_VER"
  - composer global require "sensiolabs/security-checker"
  - composer install

script:
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check
  #- docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --dry-run ./

notifications:
  on_success: never
  on_failure: always
  email:  gui.quirin@hotmail.fr

